export const ListadoPropiedades = [
  {
    id: 1,
    title: 'Casa en la playa',
    tipoMoneda: 'U$D',
    precio: "120.000",
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Punta del Este, ', 'Maldonado'],
    comodidades: ['Piscina', 'Cocina Equipada', 'Vista al mar', 'Jardín'],
    descripcion: 'Espectacular casa frente al mar en Punta del Este',
    aceptaMascotasOptions: 'Sí',
    zona: 'Punta Ballena',
    garaje: 'Sí',
    m2Edificados: 400,
    m2Terreno: 1000,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2015,
    estado: 'Nuevo',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x405.9a5cfceec57b2724d2b8a9cf59acd2096fd7a575.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.45517f6aae00596c9e3060effc876f127f3bc96a.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.1c8b9c02a32b9ebcbd39925a6936329780169cb0.jpg',
    ],
  },
  {
    id: 2,
    title: 'Apartamento céntrico',
    tipoMoneda: '$',
    precio: 900,
    disposicion: 'Interno',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Centro, ', 'Montevideo '],
    comodidades: ['Aire Acondicionado', 'Terraza', 'Cocina Equipada'],
    descripcion: 'Acogedor apartamento en pleno centro de Montevideo',
    aceptaMascotasOptions: 'No',
    zona: 'Centro',
    garaje: 'No',
    m2Edificados: 80,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 1,
    dormitorios: 2,
    anioConstruccion: 2000,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.0b681f1664248bbd6cfd5f6992728b9c7b855d16.jpeg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.77001b037aa0d2285bd2dc7ab09a98bff04bcfbe.jpeg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.9558376e8a856b8af8d9714e4a84d79fd3a01c6f.jpeg',
    ],
  },
  {
    id: 3,
    title: 'Chalet en el bosque',
    tipoMoneda: 'U$D',
    precio: "150.000",
    disposicion: 'Bosque',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Sierras de Minas, ', 'Lavalleja '],
    comodidades: ['Piscina', 'Vista al bosque', 'Parque amplio'],
    descripcion:
      'Encantador chalet rodeado de naturaleza en las Sierras de Minas',
    aceptaMascotasOptions: 'Sí',
    zona: 'Sierras de Minas',
    garaje: 'Sí',
    m2Edificados: 200,
    m2Terreno: 3000,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 1990,
    estado: 'Muy buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.e19d690e3722610e2e6908507e62e2bb521f77b4.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.6bb326564735cc812b593623b5d1fe33092733fa.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.5664db6f8b9866ba3257ed03e98b0abcf72ef751.jpg',
    ],
  },
  {
    id: 4,
    title: 'Piso en el centro histórico',
    tipoMoneda: 'U$D',
    precio: 1100,
    disposicion: 'Exterior',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Ciudad Vieja, ', 'Montevideo '],
    comodidades: ['Vista al casco antiguo', 'Terraza', 'Cocina moderna'],
    descripcion: 'Elegante piso con vistas en el corazón de la Ciudad Vieja',
    aceptaMascotasOptions: 'No',
    zona: 'Ciudad Vieja',
    garaje: 'No',
    m2Edificados: 120,
    m2Terreno: 0,
    tipoDePropiedad: 'Piso',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2012,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.c0901d12831fe2b92638bcbeac69dbb591c0a8bb.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside213x210.ab734190f8835f2f3eec1999a5a6f20e6587d15a.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.fe064b0d98b67eae8c51ef6feb13dc452c9fd7a0.jpg',
    ],
  },
  {
    id: 5,
    title: 'Terreno en las afueras',
    tipoMoneda: 'U$D',
    precio: "50.000",
    disposicion: 'Rural',
    tipoDePublicacion: 'Venta',
    ubicacion: ['San Ramón, ', 'Canelones '],
    comodidades: ['Terreno amplio', 'Vistas al campo'],
    descripcion: 'Amplio terreno rural para construir tu casa de ensueño',
    aceptaMascotasOptions: 'Sí',
    zona: 'San Ramón',
    garaje: 'No',
    m2Edificados: 0,
    m2Terreno: 5000,
    tipoDePropiedad: 'Terreno',
    baños: null,
    dormitorios: null,
    anioConstruccion: null,
    estado: 'Sin construcción',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.148805_PBI-2979-TRA_327.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.148805_PBI-2979-TRA_769.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.148805_PBI-2979-TRA_363.jpg',
    ],
  },
  {
    id: 6,
    title: 'Apartamento en la costa',
    tipoMoneda: 'U$D',
    precio: 950,
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Atlántida, ', 'Canelones '],
    comodidades: [
      'Balcón con vistas',
      'Cocina Equipada',
      'Piscina comunitaria',
    ],
    descripcion: 'Agradable apartamento con vistas al mar en Atlántida',
    aceptaMascotasOptions: 'Sí',
    zona: 'Atlántida',
    garaje: 'Sí',
    m2Edificados: 70,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 1,
    dormitorios: 2,
    anioConstruccion: 2005,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.d68df1eab758e790a8540133dbe67c0ec834afc4.jpeg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.806c65c309b88ea6bf61f0a4aba6c86933cf423e.jpeg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.fa0aea5c8ac33e1f21e2b9c9f5936d3522e58e1e.jpeg',
    ],
  },
  {
    id: 7,
    title: 'Casa de campo',
    tipoMoneda: 'U$D',
    precio: "85.000",
    disposicion: 'Campo',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Tacuarembó, ', 'Tacuarembó'],
    comodidades: ['Terreno amplio', 'Piscina', 'Parque con árboles'],
    descripcion: 'Tranquila casa de campo en Tacuarembó',
    aceptaMascotasOptions: 'Sí',
    zona: 'Tacuarembó',
    garaje: 'Sí',
    m2Edificados: 150,
    m2Terreno: 10000,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 1995,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.37_CBR-CBR-863_353.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.37_CBR-CBR-863_149.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.37_CBR-CBR-863_221.jpg',
    ],
  },
  {
    id: 8,
    title: 'Apartamento en Malvín Norte',
    tipoMoneda: 'U$D',
    precio: 1000,
    disposicion: 'Contrafrente',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Malvín Norte, ', 'Montevideo'],
    comodidades: ['Balcón', 'Cocina Equipada', 'Aire Acondicionado'],
    descripcion: 'Amplio apartamento en Malvín Norte, cerca de la playa',
    aceptaMascotasOptions: 'Sí',
    zona: 'Malvín Norte',
    garaje: 'Sí',
    m2Edificados: 90,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2008,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.29cc696813c5080938b51fa11289a7b8af140471.jpeg#HASTH',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.832e1c9851819d306fd43e6f968a2a07d90c17ca.jpeg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.6b4322cc72b1b82d70f9fa6540d405c0ed7aa357.jpeg',
    ],
  },
  {
    id: 9,
    title: 'Casa de playa en La Paloma',
    tipoMoneda: 'U$D',
    precio: "130.000",
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Venta',
    ubicacion: ['La Paloma, ', 'Rocha'],
    comodidades: ['Piscina', 'Vista al mar', 'Jardín amplio'],
    descripcion: 'Hermosa casa de playa en La Paloma, frente al mar',
    aceptaMascotasOptions: 'Sí',
    zona: 'La Paloma',
    garaje: 'Sí',
    m2Edificados: 180,
    m2Terreno: 800,
    tipoDePropiedad: 'Casa',
    baños: 3,
    dormitorios: 4,
    anioConstruccion: 2013,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.62f0ea87cfc8ca0be0bc0bab4c758645eb535903.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.1d6f5c6e48852dd57546d8d77760d6f7b2376c99.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.f8995f7548f9d7f0483963cdf008c59001802fd6.jpg',
    ],
  },
  {
    id: 10,
    title: 'Apartamento en Carrasco',
    tipoMoneda: 'U$D',
    precio: 1500,
    disposicion: 'Frente al río',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Carrasco, ', 'Montevideo'],
    comodidades: [
      'Balcón con vistas al río',
      'Cocina moderna',
      'Aire Acondicionado',
    ],
    descripcion: 'Elegante apartamento en Carrasco, con vistas al río',
    aceptaMascotasOptions: 'No',
    zona: 'Carrasco',
    garaje: 'Sí',
    m2Edificados: 110,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2017,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.89056_CW206866_266.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.89056_CW206866_769.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.89056_CW206866_181.jpg',
    ],
  },
  {
    id: 11,
    title: 'Casa en las sierras',
    tipoMoneda: 'U$D',
    precio: "95.000",
    disposicion: 'Sierra',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Sierras de Rocha, ', 'Rocha'],
    comodidades: [
      'Terreno amplio',
      'Vistas a las sierras',
      'Jardín con árboles',
    ],
    descripcion:
      'Encantadora casa en las Sierras de Rocha, rodeada de naturaleza',
    aceptaMascotasOptions: 'Sí',
    zona: 'Sierras de Rocha',
    garaje: 'Sí',
    m2Edificados: 120,
    m2Terreno: 3000,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2005,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.122103_CW204827_364.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW204827_189.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.122103_CW204827_75.jpg',
    ],
  },
  {
    id: 12,
    title: 'Piso en el Prado',
    tipoMoneda: 'U$D',
    precio: 850,
    disposicion: 'Frente al parque',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Prado, ', 'Montevideo'],
    comodidades: [
      'Balcón con vistas al parque',
      'Cocina Equipada',
      'Aire Acondicionado',
    ],
    descripcion: 'Amplio piso con vistas al Prado, junto al parque',
    aceptaMascotasOptions: 'Sí',
    zona: 'Prado',
    garaje: 'Sí',
    m2Edificados: 100,
    m2Terreno: 0,
    tipoDePropiedad: 'Piso',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2010,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.173160210_9248_19.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.173160210_9248_188.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.173160210_9248_874.jpg',
    ],
  },
  {
    id: 13,
    title: 'Casa en la costa de Rocha',
    tipoMoneda: 'U$D',
    precio: "110.000",
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Rocha, ', 'Rocha'],
    comodidades: ['Piscina', 'Vista al mar', 'Jardín con palmeras'],
    descripcion: 'Espectacular casa frente al mar en la costa de Rocha',
    aceptaMascotasOptions: 'Sí',
    zona: 'Rocha',
    garaje: 'Sí',
    m2Edificados: 160,
    m2Terreno: 1000,
    tipoDePropiedad: 'Casa',
    baños: 3,
    dormitorios: 4,
    anioConstruccion: 2014,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.f41a6c00955153cfff2b9c9050f7e788e451e0cd.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.017cdef22fad0eb811cd143a2f015755b0727b84.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.accacd3227df9edfa2cec4ad66d1bf1e2d008d62.jpg',
    ],
  },
  {
    id: 14,
    title: 'Apartamento en Malvín Sur',
    tipoMoneda: 'U$D',
    precio: 950,
    disposicion: 'Contrafrente',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Malvín Sur, ', 'Montevideo'],
    comodidades: [
      'Balcón con vistas al mar',
      'Cocina Equipada',
      'Aire Acondicionado',
    ],
    descripcion: 'Moderno apartamento en Malvín Sur, a pasos de la playa',
    aceptaMascotasOptions: 'No',
    zona: 'Malvín Sur',
    garaje: 'Sí',
    m2Edificados: 85,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2011,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside671x413.cedc394241e2f346c8a54bedc06a6664e555bf43.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.ba32d1bfe6aa02b7f0a6978c7199f74c31cb04f9.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.d0e647c2c3977889ab900a3f8370e3b78903b8b8.jpg',
    ],
  },
  {
    id: 15,
    title: 'Casa en las sierras de Lavalleja',
    tipoMoneda: 'U$D',
    precio: "100.000",
    disposicion: 'Sierra',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Sierras de Lavalleja, ', 'Lavalleja'],
    comodidades: ['Terreno amplio', 'Vistas a las sierras', 'Piscina'],
    descripcion:
      'Hermosa casa en las Sierras de Lavalleja, rodeada de paz y naturaleza',
    aceptaMascotasOptions: 'Sí',
    zona: 'Sierras de Lavalleja',
    garaje: 'Sí',
    m2Edificados: 140,
    m2Terreno: 5000,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2007,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.37_CBR-CBR-1009_41.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.37_CBR-CBR-1009_141.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.37_CBR-CBR-1009_32.jpg',
    ],
  },
  {
    id: 16,
    title: 'Apartamento en Punta Carretas',
    tipoMoneda: 'U$D',
    precio: 1200,
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Punta Carretas, ', 'Montevideo'],
    comodidades: [
      'Balcón con vistas al mar',
      'Cocina moderna',
      'Aire Acondicionado',
    ],
    descripcion: 'Espectacular apartamento en Punta Carretas con vistas al mar',
    aceptaMascotasOptions: 'Sí',
    zona: 'Punta Carretas',
    garaje: 'Sí',
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2018,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.e4224723df4cee089e6a86b41f3137883f8233a2.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.6dc31347a986adf799b1535bc6a91b1471073dbc.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.53b375395cee64224b60a873fe58791a33dc1c0b.jpg',
    ],
  },
  {
    id: 17,
    title: 'Casa en la costa de Canelones',
    tipoMoneda: 'U$D',
    precio: "110.000",
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Venta',
    ubicacion: ['Canelones, ', 'Canelones'],
    comodidades: ['Piscina', 'Vista al mar', 'Parque con palmeras'],
    descripcion:
      'Casa frente al mar en la costa de Canelones, ideal para relajarse',
    aceptaMascotasOptions: 'Sí',
    zona: 'Canelones',
    garaje: 'Sí',
    m2Edificados: 160,
    m2Terreno: 800,
    tipoDePropiedad: 'Casa',
    baños: 3,
    dormitorios: 4,
    anioConstruccion: 2015,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.ca33ce8343c7ae26fad657fde78eb344f8bf552f.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.7c8d08037304ea7ac323ddc161e03803ec06b032.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.eefafa1fc18e4f47d5aa087f2afa7d0fe79b52ee.jpg',
    ],
  },
  {
    id: 18,
    title: 'Apartamento en Buceo',
    tipoMoneda: 'U$D',
    precio: 950,
    disposicion: 'Frente al río',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Buceo, ', 'Montevideo'],
    comodidades: [
      'Balcón con vistas al río',
      'Cocina Equipada',
      'Aire Acondicionado',
    ],
    descripcion: 'Moderno apartamento en Buceo, con hermosas vistas al río',
    aceptaMascotasOptions: 'No',
    zona: 'Buceo',
    garaje: 'Sí',
    m2Edificados: 85,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2010,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.c30657c4f71f8178298caf41e55037b714767b99.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2487x1161.655eb6a99f706ddcced0ea336f48bb0fdeb3d635.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.2ff0ad8494c4b3587b275bdda9c4ad6621cd9ef6.jpg',
    ],
  },
  {
    id: 19,
    title: 'Casa de playa en La Pedrera',
    tipoMoneda: 'U$D',
    precio: "130.000",
    disposicion: 'Frente al mar',
    tipoDePublicacion: 'Venta',
    ubicacion: ['La Pedrera, ', 'Rocha'],
    comodidades: ['Piscina', 'Vista al mar', 'Amplio jardín con palmeras'],
    descripcion:
      'Casa de playa en La Pedrera, con vistas al mar y mucha privacidad',
    aceptaMascotasOptions: 'Sí',
    zona: 'La Pedrera',
    garaje: 'Sí',
    m2Edificados: 180,
    m2Terreno: 800,
    tipoDePropiedad: 'Casa',
    baños: 3,
    dormitorios: 4,
    anioConstruccion: 2013,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside654x400.b0df65e98b7c75737eac873192f00b0cc4acc38e.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.4940d47bb35a3ebcdddbcc3661aff27b1bd64937.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.5ad3f452525a70f4e97c4a5aa8ce41e0e281ce95.jpg',
    ],
  },
  {
    id: 20,
    title: 'Apartamento en Ciudad de la Costa',
    tipoMoneda: 'U$D',
    precio: "120/Noche",
    disposicion: 'Frente al río',
    tipoDePublicacion: 'Alquiler',
    ubicacion: ['Ciudad de la Costa, ', 'Canelones'],
    comodidades: [
      'Balcón con vistas al río',
      'Cocina moderna',
      'Aire Acondicionado',
    ],
    descripcion: 'Amplio apartamento en Ciudad de la Costa, con vistas al río',
    aceptaMascotasOptions: 'Sí',
    zona: 'Ciudad de la Costa',
    garaje: 'Sí',
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2017,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.cdc1eb71c8e02f0c9301d92f0c3909294771f887.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.72cfc7551dac430758cf38c168e08c7b811fd5aa.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.f64a326f1c3c4fc8af80b92c4e956b95a87f0802.jpg',
    ],
  },
  {
    id: 21,
    title: 'Apartamento en Ciudad de la Costa',
    tipoMoneda: 'U$D',
    precio: "100/Noche",
    disposicion: 'Frente al río',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Ciudad de la Costa, ', 'Canelones'],
    comodidades: [
      'Balcón con vistas al río',
      'Cocina moderna',
      'Aire Acondicionado',
    ],
    descripcion: 'Amplio apartamento en Ciudad de la Costa, con vistas al río',
    aceptaMascotasOptions: 'Sí',
    zona: 'Ciudad de la Costa',
    garaje: 'Sí',
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2017,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.cdc1eb71c8e02f0c9301d92f0c3909294771f887.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.72cfc7551dac430758cf38c168e08c7b811fd5aa.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside500x1.f64a326f1c3c4fc8af80b92c4e956b95a87f0802.jpg',
    ],
  },
  {
    id: 22,
    title: 'Casa en Carrasco',
    tipoMoneda: 'U$D',
    precio: "150/Noche",
    disposicion: 'Jardín trasero',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Carrasco, ', 'Montevideo'],
    comodidades: [
      'Amplio jardín',
      'Cocina equipada',
      'Calefacción central',
    ],
    descripcion: 'Hermosa casa en Carrasco con jardín trasero',
    aceptaMascotasOptions: 'Sí',
    zona: 'Carrasco',
    garaje: 'Sí',
    m2Edificados: 120,
    m2Terreno: 300,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2015,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7605-TRA_794.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7605-TRA_346.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7605-TRA_675.jpg',
    ],
  },
  {
    id: 23,
    title: 'Apartamento en Carrasco',
    tipoMoneda: 'U$D',
    precio: "110/Noche",
    disposicion: 'Vista al parque',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Carrasco, ', 'Montevideo'],
    comodidades: [
      'Terraza privada',
      'Cocina con electrodomésticos modernos',
      'Piscina comunitaria',
    ],
    descripcion: 'Moderno apartamento en Carrasco con vista al parque',
    aceptaMascotasOptions: 'Sí',
    zona: 'Carrasco',
    garaje: 'Sí',
    m2Edificados: 100,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2015,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.859db9856e7480108d8aa5122ae188865e429267.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.bec4fce7ce3fd879f81a4c91c141fdb69b1ffe47.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.523a0ae645937d3b3b04387bf95923d45ad6e323.jpg',
    ],
  },
  {
    id: 24,
    title: 'Casa en Colonia',
    tipoMoneda: 'U$D',
    precio: "130/Noche",
    disposicion: 'Jardín frontal',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Nueva Helvecia, ','Colonia'],
    comodidades: [
      'Amplio patio con jardín',
      'Cocina estilo rústico',
      'Chimenea',
    ],
    descripcion: 'Encantadora casa en Colonia con hermoso jardín frontal',
    aceptaMascotasOptions: 'Sí',
    zona: 'Centro histórico',
    garaje: 'No',
    m2Edificados: 150,
    m2Terreno: 300,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2008,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-464-TRA_772.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-464-TRA_677.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-464-TRA_574.jpg',
    ],
  },
  {
    id: 25,
    title: 'Apartamento en Pocitos',
    tipoMoneda: 'U$D',
    precio: "95/Noche",
    disposicion: 'Vista a la ciudad',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Pocitos, ', 'Montevideo'],
    comodidades: [
      'Balcón con vista panorámica',
      'Cocina con barra desayunadora',
      'Gimnasio en el edificio',
    ],
    descripcion: 'Luminoso apartamento en Pocitos con vista a la ciudad',
    aceptaMascotasOptions: 'No',
    zona: 'Pocitos',
    garaje: 'Sí',
    m2Edificados: 85,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 1,
    dormitorios: 1,
    anioConstruccion: 2012,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-3926-TRA_132.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-3926-TRA_879.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-3926-TRA_623.jpg',
    ],
  },
  {
    id: 26,
    title: 'Casa en La Paloma',
    tipoMoneda: 'U$D',
    precio: "110/Noche",
    disposicion: 'Vista al océano',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['La Paloma, ', 'Rocha'],
    comodidades: [
      'Patio con acceso directo a la playa',
      'Cocina amplia',
      'Churrasquera al aire libre',
    ],
    descripcion: 'Encantadora casa en La Paloma con impresionante vista al océano',
    aceptaMascotasOptions: 'Sí',
    zona: 'Balconada',
    garaje: 'No',
    m2Edificados: 120,
    m2Terreno: 400,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2016,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-5893-TRA_449.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-5893-TRA_698.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-5893-TRA_618.jpg',
    ],
  },
  {
    id: 27,
    title: 'Apartamento en Punta Carretas',
    tipoMoneda: 'U$D',
    precio: "130/Noche",
    disposicion: 'Vista al parque',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Punta Carretas, ', 'Montevideo'],
    comodidades: [
      'Terraza con vista al parque Rodó',
      'Cocina moderna',
      'Piscina en el edificio',
    ],
    descripcion: 'Moderno apartamento en Punta Carretas con vista al parque',
    aceptaMascotasOptions: 'No',
    zona: 'Punta Carretas',
    garaje: 'Sí',
    m2Edificados: 110,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2014,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-4102-TRA_52.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-4102-TRA_649.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-4102-TRA_192.jpg',
    ],
  },
  {
    id: 28,
    title: 'Casa en Atlántida',
    tipoMoneda: 'U$D',
    precio: "100/Noche",
    disposicion: 'Jardín con piscina',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Atlántida, ', 'Canelones'],
    comodidades: [
      'Parrillero techado',
      'Cocina con isla',
      'Aire acondicionado en todas las habitaciones',
    ],
    descripcion: 'Espectacular casa en Atlántida con jardín y piscina privados',
    aceptaMascotasOptions: 'Sí',
    zona: 'Centro',
    garaje: 'Sí',
    m2Edificados: 160,
    m2Terreno: 600,
    tipoDePropiedad: 'Casa',
    baños: 3,
    dormitorios: 3,
    anioConstruccion: 2013,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-1919-TRA_820.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-1919-TRA_988.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-1919-TRA_380.jpg',
    ],
  },
  {
    id: 29,
    title: 'Apartamento en Malvín',
    tipoMoneda: 'U$D',
    precio: "90/Noche",
    disposicion: 'Vista al mar',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Malvín, ', 'Montevideo'],
    comodidades: [
      'Balcón con vista panorámica al mar',
      'Cocina con electrodomésticos de acero inoxidable',
      'Piscina en el complejo',
    ],
    descripcion: 'Acogedor apartamento en Malvín con hermosa vista al mar',
    aceptaMascotasOptions: 'Sí',
    zona: 'Rambla',
    garaje: 'Sí',
    m2Edificados: 95,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 1,
    dormitorios: 1,
    anioConstruccion: 2011,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-6591-TRA_971.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-6591-TRA_249.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-6591-TRA_112.jpg',
    ],
  },
  {
    id: 30,
    title: 'Casa en Sauce',
    tipoMoneda: 'U$D',
    precio: "95/Noche",
    disposicion: 'Gran patio trasero',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Sauce, ', 'Canelones'],
    comodidades: [
      'Barbacoa con horno de leña',
      'Cocina estilo campo',
      'Habitación principal en suite',
    ],
    descripcion: 'Amplia casa en Sauce con hermoso patio trasero',
    aceptaMascotasOptions: 'Sí',
    zona: 'Centro',
    garaje: 'No',
    m2Edificados: 130,
    m2Terreno: 400,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2009,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-327-TRA_173.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-327-TRA_815.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-327-TRA_257.jpg',
    ],
  },
  {
    id: 31,
    title: 'Apartamento en Malvín Norte',
    tipoMoneda: 'U$D',
    precio: "100/Noche",
    disposicion: 'Vista a la ciudad',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Malvín Norte, ', 'Montevideo'],
    comodidades: [
      'Terraza amplia',
      'Cocina con barra desayunadora',
      'Estacionamiento privado',
    ],
    descripcion: 'Moderno apartamento en Malvín Norte con vista a la ciudad',
    aceptaMascotasOptions: 'Sí',
    zona: 'Malvín Norte',
    garaje: 'Sí',
    m2Edificados: 110,
    m2Terreno: 0,
    tipoDePropiedad: 'Apartamento',
    baños: 2,
    dormitorios: 2,
    anioConstruccion: 2016,
    estado: 'Excelente estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7287-TRA_24.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7287-TRA_569.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.203121_SIP-7287-TRA_823.jpg',
    ],
  },
  {
    id: 32,
    title: 'Casa en Las Piedras',
    tipoMoneda: 'U$D',
    precio: "90/Noche",
    disposicion: 'Patio con piscina',
    tipoDePublicacion: 'Alquiler Temporal',
    ubicacion: ['Las Piedras, ', 'Canelones'],
    comodidades: [
      'Cocina con isla y electrodomésticos modernos',
      'Parrillero techado',
      'Aire acondicionado en todas las habitaciones',
    ],
    descripcion: 'Encantadora casa en Las Piedras con patio y piscina privados',
    aceptaMascotasOptions: 'Sí',
    zona: 'Centro',
    garaje: 'Sí',
    m2Edificados: 120,
    m2Terreno: 500,
    tipoDePropiedad: 'Casa',
    baños: 2,
    dormitorios: 3,
    anioConstruccion: 2014,
    estado: 'Buen estado',
    imgsrc: [
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-189-TRA_316.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-189-TRA_77.jpg',
      'https://cdn2.infocasas.com.uy/repo/img/th.outside2528x1143.173266105_GSL-189-TRA_272.jpg',
    ],
  }
]

export const ListadoLocalidades = [
  'Artigas',
  'Canelones',
  'Cerro Largo',
  'Colonia',
  'Durazno',
  'Flores',
  'Florida',
  'Lavalleja',
  'Maldonado',
  'Montevideo',
  'Paysandu',
  'Río Negro',
  'Rivera',
  'Rocha',
  'Salto',
  'San José',
  'Soriano',
  'Tacuarembo',
  'Treinta y Tres',
]
export const ListadoTipoDePropiedad = [
  'Casa',
  'Apartamento',
  'Terreno',
  'Local Comercial',
  'Oficina',
  'Chacra o Campo',
  'Garage o Cochera',
  'Negocio Especial',
  'Edificio',
  'Hotel',
  'Local industrial o galpón',
  'Otro',
]
export const ListadoCantidadDormitorios = [
  'Monoambiente',
  '1',
  '2',
  '3',
  '4',
  '5+',
]
export const ListadoAtributos = [
  'Nombre',
  'Ubicacion',
  'Disposicion',
  'Año de Construccion',
  'M² edificados',
  'M² del terreno',
]
export const nombreDeGuardadoDeLosAtributos = [
  'title',
  'ubicacion',
  'disposicion',
  'anioConstruccion',
  'm2Edificados',
  'm2Terreno',
]
export const ListadotypesDeAtributos = [
  'text',
  'text',
  'text',
  'number',
  'number',
  'number',
]

export const ListadoBaños = ['1', '2', '3', '4', '5+']
export const ListadoOpciones = ['Si', 'No']
export const ListadoTipoDePublicacion = [
  'Alquiler',
  'Venta',
  'Alquiler Temporal',
]
export const ListadoMoneda = ['Pesos', 'Dolares']
export const ListadoDeEstado = [
  'Nuevo',
  'Usado',
  'En construccion',
  'Remodelado',
  'A estrenar',
  'En buen estado',
  'Para remodelar',
  'Para demoler',
  'Otros',
]
export const ListadoComodidades = [
  'Piscina',
  'Garage',
  'Jardin',
  'Terraza',
  'Calefaccion',
  'Aire acondicionado',
  'Gimnasio',
  'Vista al mar',
  'Armarios empotrado',
  'Cocina equipada',
  'Chimenea',
  'Ascensor',
  'Lavandería',
  'Alarma de seguridad',
  'Sistema de videovigilancia',
  'Acceso para discapacitados',
  'Trastero',
  'Suelos de madera',
  'Sistema de riego automático',
  'Zona de barbacoa',
]
